name: Template

on:
  push:
    branches: [ci/add-template-test]
  workflow_dispatch:

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install (with cache)
        uses: bahmutov/npm-install@v1

      - name: Pretty
        run: yarn pretty:fix

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Create Template (npx)
        run: |
          pwd
          cd ${{ github.workspace }}/..
          pwd
          npx create-react-app npx-test --template file:${{ github.workspace }}
          cd npx-test
          pwd
          npm run test
          npm run build
          npm run build:archive

      - name: Create Template (yarn)
        run: |
          pwd
          cd ${{ github.workspace }}/..
          pwd
          yarn create react-app yarn-test --template file:${{ github.workspace }}
          cd yarn-test
          pwd
          yarn test
          yarn build
          yarn build:archive
